# DO NOT CHANGE THIS PART!!!
# #########################################
dailyLastScheduledTime: 1720757055869
weeklyLastScheduledTime: 1720745355824
monthlyLastScheduledTime: 1718815517777
# #########################################
log_level:
- INFO
- WARNING
- ERROR
# - SPAWNERS
# - KILL_EVENT
# - CUSTOM_MOBS
# - DEBUG
# - RANKING_REWARDS

blocks_rewards:
  DIAMOND_ORE: 1.3
  DIAMOND_BLOCK: 1.3
  EMERALD_ORE: 1.2
  EMERALD_BLOCK: 1.2
  GOLD_ORE: 1.1
  GOLD_BLOCK: 1.1
  IRON_ORE: 1
  IRON_BLOCK: 1
  BEACON: 100
  YELLOW_GLAZED_TERRACOTTA: 10
  NETHERITE_BLOCK: 1.6
  CRYING_OBSIDIAN: 1.5
  OBSIDIAN: 1.4
  YELLOW_WOOL: 20
  COBBLESTONE: 0.1
  PURPLE_WOOL: 0.5
block_base: 0.1
antyweb_elo_cost: 0.1
Infinite_firework_cooldown: 450
Flamethrower_cooldown: 1500
Zephyr_cooldown: 1500
Mob_Damage_Lore: "&6&lMob Damage "
Mob_Defense_Lore: "&6&lMob Defense "
Average_Damage_Lore: "&6&lAverage Damage +"
Current_Bonus_String: "&6&lCurrent Bonus: "
Enchant_Item_Name: "&57&lEnchant Item"
Enchant_Item_Lore:
- "&7Removes current the Average Damage bonus"
- "&7from the item and adds new one."
event_items_with_username:
- DIAMOND_PICKAXE
- DIAMOND_AXE
- GOLDEN_AXE
- IRON_AXE
- STONE_AXE
